# -*- coding: utf-8 -*-

__author__ = 'Amar Sood (tekacs)'

from .lastfm import LastFMAPIObject, APIMeta

class Artist(LastFMAPIObject):
    """A map to the last.fm Artist namespace."""

    __metaclass__ = APIMeta
    # _methods generated by lastfm._auth_filter
    _methods = {
        'get': [
            'getCorrection',
            'getEvents',
            'getInfo',
            'getPastEvents',
            'getPodcast',
            'getShouts',
            'getSimilar',
            'getTags',
            'getTopAlbums',
            'getTopFans',
            'getTopTags',
            'getTopTracks',
            'search'
        ],
        'post': [
            'addTags',
            'removeTag',
            'share',
            'shout'
        ]
    }

#    def get_info(json):
#        """This is an example, simplistic transformer.
#        json contains:
#
#            - bio
#            - streamable
#            - ontour
#            - stats
#            - name
#            - tags
#            - url
#            - image
#            - mbid
#            - bandmembers
#            - similar
#        """
#        return type('Info', (object,), json)